<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ai-service\GraphGuard.AI\GraphGuard.AI.csproj" />
    <ProjectReference Include="..\GraphGuard.Domain\GraphGuard.Domain.csproj" />
    <ProjectReference Include="..\GraphGuard.Infrastructure\GraphGuard.Infrastructure.csproj" />
  </ItemGroup>

</Project>
